// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentFile():Promise<main.CurrentFile>;

export function Greet(arg1:string):Promise<string>;

export function SetCurrentFile(arg1:number,arg2:number):Promise<void>;

export function WriteImage(arg1:string):Promise<boolean>;
