// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetCurrentFile(arg1, arg2) {
  return window['go']['main']['App']['SetCurrentFile'](arg1, arg2);
}

export function WriteImage(arg1) {
  return window['go']['main']['App']['WriteImage'](arg1);
}
