// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {piet} from '../models';
import {main} from '../models';

export function CharOut(arg1:string):Promise<void>;

export function DebugStep(arg1:string):Promise<piet.DebugInfo>;

export function EmitInterpreterState():Promise<void>;

export function GetCurrentFile():Promise<main.CurrentFile>;

export function GetHelp():Promise<string>;

export function GetRecent():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function NumOut(arg1:string):Promise<void>;

export function OpenImage():Promise<string>;

export function OpenImageFromDefaultFolder():Promise<void>;

export function SetCurrentFile(arg1:number,arg2:number):Promise<void>;

export function WriteImage(arg1:string):Promise<string>;

export function WriteImageAndDebug(arg1:string):Promise<piet.DebugInfo>;

export function WriteImageAndRun(arg1:string):Promise<boolean>;
