// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function GetHelp() {
  return window['go']['main']['App']['GetHelp']();
}

export function GetRecent() {
  return window['go']['main']['App']['GetRecent']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenImage() {
  return window['go']['main']['App']['OpenImage']();
}

export function OpenImageFromDefaultFolder() {
  return window['go']['main']['App']['OpenImageFromDefaultFolder']();
}

export function SetCurrentFile(arg1, arg2) {
  return window['go']['main']['App']['SetCurrentFile'](arg1, arg2);
}

export function WriteImage(arg1) {
  return window['go']['main']['App']['WriteImage'](arg1);
}

export function WriteImageAndRun(arg1) {
  return window['go']['main']['App']['WriteImageAndRun'](arg1);
}
